version: '3.4' # Versão do docker compose
services:
  app:
    image: tomcat
    container_name: app 
    ports:
      - 8080:80
    volumes:
      - ./store-system/store-system.war:/usr/local/tomcat/webapps/store-system.war
      - ./store-system/store-system:/usr/local/tomcat/webapps/store-system
    depends_on: 
      - db
  db:
    image: mysql
    container_name: msql
    environment: 
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=




# sudo docker-compose up